---
#################################
# Data about the map, and tiles #
#################################

# The number of bombs
Bombs: 10

# Number of tiles in the map
MapSize:
  x: 5
  y: 10

# Pixel size of each tile
TileSize:
  x: 50
  y: 50

---
##########################
# Data about tile colors #
##########################

# The color of an unexplored tile
HiddenColor:
  r: 0
  g: 0
  b: 0
  a: 0

# The color of an explored (empty) tile
ExposedColor:
  r: 0
  g: 0
  b: 0
  a: 0

# The color of a flagged tile
FlagColor:
  r: 0
  g: 0
  b: 0
  a: 0

# The color of a bomb tile
BombColor:
  r: 0
  g: 0
  b: 0
  a: 0

# The color of bomb number (text) surrounding a tile
TextColor:
  r: 0
  g: 0
  b: 0
  a: 0
...
